### ISSUE TITLE
Sistema nao navega

### ISSUE THREAD

**Issue by JonesBalada** [fgsl/econference#67]
Com $ composer run --timeout 0 serve

Tinha aparecido a tela inicial no firefox e ao clicar me Sediadoras, apareceu isso:

> php -S 0.0.0.0:8080 -t public public/index.php
[Tue Oct 31 10:36:36 2017] PHP Warning:  The use statement with non-compound name 'Sediadoras' has no effect in /var/www/html/alisson/siscon/config/modules.config.php on line 2
[Tue Oct 31 10:36:36 2017] PHP Fatal error:  Uncaught Error: Call to undefined method Closure::__set_state() in /var/www/html/alisson/siscon/data/cache/module-config-cache.application.config.cache.php:24
Stack trace:
#0 /var/www/html/alisson/siscon/vendor/zendframework/zend-modulemanager/src/Listener/ConfigListener.php(392): include()
#1 /var/www/html/alisson/siscon/vendor/zendframework/zend-modulemanager/src/Listener/ConfigListener.php(70): Zend\ModuleManager\Listener\ConfigListener->getCachedConfig()
#2 /var/www/html/alisson/siscon/vendor/zendframework/zend-modulemanager/src/Listener/DefaultListenerAggregate.php(112): Zend\ModuleManager\Listener\ConfigListener->__construct(Object(Zend\ModuleManager\Listener\ListenerOptions))
#3 /var/www/html/alisson/siscon/vendor/zendframework/zend-modulemanager/src/Listener/DefaultListenerAggregate.php(42): Zend\ModuleManager\Listener\DefaultListenerAggregate->getConfigListener()
#4 /var/www/html/alisson/siscon/vendor/zendframework/zend-mvc/src/Service/ModuleManagerFactory.php(77): Zend\ModuleManager\Listener\Default in /var/www/html/alisson/siscon/data/cache/module-config-cache.application.config.cache.php on line 24

Depois disso tentei acessar no chromium:
[Tue Oct 31 10:37:58 2017] PHP Fatal error:  Uncaught Error: Call to undefined method Closure::__set_state() in /var/www/html/alisson/siscon/data/cache/module-config-cache.application.config.cache.php:24
Stack trace:
#0 /var/www/html/alisson/siscon/vendor/zendframework/zend-modulemanager/src/Listener/ConfigListener.php(392): include()
#1 /var/www/html/alisson/siscon/vendor/zendframework/zend-modulemanager/src/Listener/ConfigListener.php(70): Zend\ModuleManager\Listener\ConfigListener->getCachedConfig()
#2 /var/www/html/alisson/siscon/vendor/zendframework/zend-modulemanager/src/Listener/DefaultListenerAggregate.php(112): Zend\ModuleManager\Listener\ConfigListener->__construct(Object(Zend\ModuleManager\Listener\ListenerOptions))
#3 /var/www/html/alisson/siscon/vendor/zendframework/zend-modulemanager/src/Listener/DefaultListenerAggregate.php(42): Zend\ModuleManager\Listener\DefaultListenerAggregate->getConfigListener()
#4 /var/www/html/alisson/siscon/vendor/zendframework/zend-mvc/src/Service/ModuleManagerFactory.php(77): Zend\ModuleManager\Listener\Default in /var/www/html/alisson/siscon/data/cache/module-config-cache.application.config.cache.php on line 24

Repare que estou executando tudo dentro da pasta /var/www/html/alisson/siscon

**Comment by fgsl** [comment]
- O problema ocorre quando o cache está habilitado
- Closures não são cacheáveis
- As closures foram substituídas por classes
- Foi criada uma abstração de fábrica para controlador e outra para mapeador
objeto-relacional

@JonesBalada, pode atualizar e testar novamente.
