### ISSUE TITLE
Erro ao Adicionar trabalhos

### ISSUE THREAD

**Issue by JonesBalada** [fgsl/econference#71]
Passos:

* criar categoria com nome 'cat1nom'
* clicar em 'Trabalhos', depois 'Adicionar trabalhos'
* Preencher com: Resumo: 'tbl1res', Tipo: '1', categoria: 'cat1nom'
* Clicar em 'gravar'

Message:

    Field 'codigo' doesn't have a default value

Stack trace:

    #0 /var/www/html/alisson/siscon/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(308): Zend\Db\Adapter\Driver\Mysqli\Statement->execute()
    #1 /var/www/html/alisson/siscon/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(264): Zend\Db\TableGateway\AbstractTableGateway->executeInsert(Object(Zend\Db\Sql\Insert))
    #2 /var/www/html/alisson/siscon/module/Trabalhos/src/Model/TrabalhoTable.php(22): Zend\Db\TableGateway\AbstractTableGateway->insert(Array)
    #3 /var/www/html/alisson/siscon/module/Trabalhos/src/Controller/IndexController.php(61): Trabalhos\Model\TrabalhoTable->save(Object(Trabalhos\Model\Trabalho))
    #4 /var/www/html/alisson/siscon/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): Trabalhos\Controller\IndexController->saveAction()
    #5 /var/www/html/alisson/siscon/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
    #6 /var/www/html/alisson/siscon/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
    #7 /var/www/html/alisson/siscon/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(106): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
    #8 /var/www/html/alisson/siscon/vendor/zendframework/zend-mvc/src/DispatchListener.php(138): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
    #9 /var/www/html/alisson/siscon/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
    #10 /var/www/html/alisson/siscon/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
    #11 /var/www/html/alisson/siscon/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
    #12 /var/www/html/alisson/siscon/public/index.php(40): Zend\Mvc\Application->run()
    #13 {main}

**Comment by JonesBalada** [comment]
Estou tratando essa issue.

**Comment by fgsl** [comment]
@JonesBalada, está corrigido, mas precisa alterar a tabela trabalhos, porque o script não marcou o campo codigo como AUTO_INCREMENT. Se for criado do zero agora, vai ficar certo.
