### ISSUE TITLE
O log da aplicacao nao deve ser armazenado no repositorio.

### ISSUE THREAD

**Issue by JonesBalada** [fgsl/econference#73]
O log da aplicacao nao deve ser armazenado no repositorio.

Jah estou tratando essa issue.

**Comment by fgsl** [comment]
@Thiagoaugusto58 e @jennifersene, o @JonesBalada percebeu uma falha nossa: o versionamento de dados de teste. Temos que tomar cuidado para não versionar nenhum arquivo que tenha dados que realmente possam ser publicados. O arquivo foi removido do controle de versão e apagado do versionamento atual, mas os commits anteriores ainda permitem ver qual era seu conteúdo.

Vamos usar essa falha para melhorar nosso processo. Vamos criar testes automatizados para manter a estabilidade do projeto.
