### ISSUE TITLE
Comandos de Banco de Dados e mensagens de erros

### ISSUE THREAD

**Issue by sidneybatistafilho** [fgsl/econference#76]
Criação do banco de dados

Especificamente para MySQL

$ mysql econference < data/erm/econference.sql
ERROR 1045 (28000): Access denied for user '80711626634'@'localhost' (using password: NO)

Para qualquer banco
$ php scripts/createdatabase.php
PHP Fatal error:  Uncaught Zend\Db\Adapter\Exception\RuntimeException: The Mysqli extension is required for this adapter but the extension is not loaded in /home/80711626634/work/main/SERPRO/orgao/crsl/tarefa/econference/clone/econference/vendor/zendframework/zend-db/src/Adapter/Driver/Mysqli/Mysqli.php:167
Stack trace:
#0 /home/80711626634/work/main/SERPRO/orgao/crsl/tarefa/econference/clone/econference/vendor/zendframework/zend-db/src/Adapter/Adapter.php(87): Zend\Db\Adapter\Driver\Mysqli\Mysqli->checkEnvironment()
#1 /home/80711626634/work/main/SERPRO/orgao/crsl/tarefa/econference/clone/econference/scripts/createdatabase.php(18): Zend\Db\Adapter\Adapter->__construct(Object(Zend\Db\Adapter\Driver\Mysqli\Mysqli))
#2 {main}
  thrown in /home/80711626634/work/main/SERPRO/orgao/crsl/tarefa/econference/clone/econference/vendor/zendframework/zend-db/src/Adapter/Driver/Mysqli/Mysqli.php on line 167

**Comment by fgsl** [comment]
@sidneybatistafilho, na instrução especificamente para MySQL estavam faltando os parâmetros -u e -p para informar usuário e senha. Adicionei isso no README. Com relação à instrução para qualquer banco, faltou seguir o item Configuração do banco de dados, que diz que "O driver selecionado precisa estar instalado para que a aplicação funcione. Para informações sobre driver de banco de dados para PHP, consulte a documentação [aqui] (http://php.net/manual/pt_BR/refs.database.php)." Enfatizei isso e coloquei um exemplo para Debian.
